#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh & 
setxkbmap es &
picom -f &

feh --bg-fill ~/Imágenes/wallpaper.jpg

bspc monitor -d dev www sys doc vbox chat media gfx 

bspc config border_width         2
bspc config window_gap           2
bspc config split_ratio          0.52

bspc config focused_border_color "#14211A"
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true 

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
